CREATE TABLE IF NOT EXISTS students (
  id INT AUTO_INCREMENT PRIMARY KEY,
  name VARCHAR(255) NOT NULL,
  age INT NOT NULL,
  `group` VARCHAR(50) NOT NULL,
  email VARCHAR(255) NULL,
  grades JSON NOT NULL,
  course INT NOT NULL,
  image VARCHAR(255) NULL,
  test VARCHAR(255) NOT NULL DEFAULT ''
);

CREATE TABLE IF NOT EXISTS migrations (
  id INT AUTO_INCREMENT PRIMARY KEY,
  hash CHAR(32) NOT NULL,
  created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP
);
